### ISSUE TITLE
logthink

### ISSUE THREAD

**Issue by namkiseung** [ChoiSG/kr-redteam-playbook#2]
삭제

**Comment by ChoiSG** [comment]
안녕하세요 로그띵님, 레드팀 플레이북 메인테이너 신청을 하기 위해 해당 이슈를 만드신건가요? 만약 그렇다면 약 일주일 뒤에 이 이슈에 코멘트를 달아 결과를 말씀드리겠습니다. 팀원 신청 감사합니다!

**Comment by namkiseung** [comment]
> 안녕하세요 로그띵님, 레드팀 플레이북 메인테이너 신청을 하기 위해 해당 이슈를 만드신건가요? 만약 그렇다면 약 일주일 뒤에 이 이슈에 코멘트를 달아 결과를 말씀드리겠습니다. 팀원 신청 감사합니다!  

네

**Comment by ChoiSG** [comment]
@namkiseung 안녕하세요, 깃북을 유료플랜으로 바꾸느라 조금 늦었습니다. 레드팀 플레이북 메인테이너로 초대드리겠습니다! 비즈니스용 이메일을 남겨주시면 그리로 초대 링크를 드리겠습니다. 

정식 메인테이너 관련 처음으로 메인테이너가 되신 분은 초대 링크를 수락한 이후 4주 안에 1개의 페이지를 배포하거나 의미있는 수정/업데이트를 하셔야합니다. 그 이후에는 자격 유지를 위해 12주에 1개 이상의 페이지를 제작/업데이트 하시면 됩니다. 

위 자격 유지 관련된 정보는 최근에 추가한 것이라 잘 모르실 수도 있으니 궁금하신 점은 이메일을 통해 질문 부탁드립니다.

**Comment by namkiseung** [comment]
해당 메일로 부탁해요.


남 기 승 Kiseung Nam
Email ***@***.***
Mobile 010-9406-5290
Profile ***@***.***
-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: "Kiseung, ***@***.***>, ***@***.***>
날짜: 2022. 10. 11 오전 10:21:03
제목: Re: [ChoiSG/kr-redteam-playbook] logthink (Issue #2)

@namkiseung 안녕하세요, 깃북을 유료플랜으로 바꾸느라 조금 늦었습니다. 레드팀 플레이북 메인테이너로 초대드리겠습니다! 비즈니스용 이메일을 남겨주시면 그리로 초대 링크를 드리겠습니다.
정식 메인테이너 관련 처음으로 메인테이너가 되신 분은 초대 링크를 수락한 이후 4주 안에 1개의 페이지를 배포하거나 의미있는 수정/업데이트를 하셔야합니다. 그 이후에는 자격 유지를 위해 12주에 1개 이상의 페이지를 제작/업데이트 하시면 됩니다.
위 자격 유지 관련된 정보는 최근에 추가한 것이라 잘 모르실 수도 있으니 궁금하신 점은 이메일을 통해 질문 부탁드립니다.

**Comment by ChoiSG** [comment]
깃허브 측에서 이메일 주소를 검열처리 한 것 같습니다. 번호로 연락드리겠습니다. 개인정보 보호를 위해 위 코멘트는 지우셔도 괜찮습니다.
