### ISSUE TITLE
오탈자 및 잘못된 문맥 제보

### ISSUE THREAD

**Issue by namkiseung** [ChoiSG/kr-redteam-playbook#3]
1. 띄어쓰기 이슈
- 첫페이지 (X) -> 첫 페이지 (O)
- 관심있는 (X) -> 관심 있는 (O)

2. 오탈자 이슈
- 알맞는 (X) -> 알맞은 (O)
- 시큐리를 (X) -> 시큐리티를 (O)

##### 이슈위치 (Github) - https://github.com/ChoiSG/kr-redteam-playbook/blob/main/MISC/contributions.md

**Comment by ChoiSG** [comment]
수정되었습니다. 오탈자 제보 감사합니다.
