### ISSUE TITLE
오타 수정(레드팀이란 - 필요지식)

### ISSUE THREAD

**Issue by dLackBWarf** [ChoiSG/kr-redteam-playbook#6]
![image](https://user-images.githubusercontent.com/130160351/230621622-9e1a7fdf-02eb-4eff-aaca-e7a46501ac75.png)

필요지식 - 공격 인프라 구축 설명란에 "다다"라고 되어있습니다.

**Comment by dLackBWarf** [comment]
Labels를 추가 못했네요ㅠㅜ 수정하는 걸 찾아봤는데 없는것같아요ㅠ 관리자님이 Lables 수정해주실 수 있으시다면 감사하겠습니다.

**Comment by ChoiSG** [comment]
오타 수정 했습니다. 제보 및 기여 감사합니다!
