### ISSUE TITLE
오타 및 표현 : 인프라 관련 용어 오타

### ISSUE THREAD

**Issue by nhd0918** [ChoiSG/kr-redteam-playbook#7]
[인프라 관련 용어 오타]
- 도메인 프로팅 (Domain Fronting) -> 도메인 프론팅 (Domain Fronting)

[왜 고쳐야하는가?]
- 해당 내용을 설명하는 내용중 "도메인 프론팅" 이라는 내용이 서술 되어있는데 
  실제로 용어를 설명하는데 도메인 프로팅으로 서술이 되어있기때문입니다.

[내용 발췌]
 - 도메인 프로팅 (Domain Fronting) - CDN 인프라의 특징과 HTTP/HTTPS의 특징을 이용해 비컨이 CDN으로 콜백을 하는 것처럼 보이지만 실제로는 공격자의 리다이렉터로 콜백하는 TTP 중 하나. 도메인 프론팅에 대해서는 다른 페이지에서 서술한다.

**Comment by ChoiSG** [comment]
수정했습니다. 제보 감사합니다!
